# Creating a Pytorch Regression Model

The following cell defines a cartoon features array, with 100 datapoints and 9 features. Our task is to create a linear model to predict the values of a target variable y. In this practical we are not concerned with making the prediction itself, just in designing the network.


In [2]:
import torch

features = torch.rand(size=[100, 9], dtype=torch.float32)
print(features.shape)


torch.Size([100, 9])


In the cell below, create a model class that inherits from `torch.nn.Module`.

- Inside the class constructor, make the `super` call to delegate inheretance from the parent class.
- Then define a network of three linear layers.
- The input layer should have the same input size as the number of features in our data, and an output layer of the same size.
- Make the middle layer have the same size input and output.
- Make the final layer have an output size of 1, representing the value of our regression prediction.
- Ensure that each linear layer is separated by a nonlinear activation layer of the appropriate type.
- Finally, define the `forward` method.


In [4]:
class RegressionModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(9, 9),
            torch.nn.ReLU(),
            torch.nn.Linear(9, 1)
        )

    def forward(self, x):
        return self.layers(x)


Now create an instance of the model, and check that the forward method works by passing the features to the model.


In [6]:
# Create an instance of `RegressionModel`
model = RegressionModel()

# Pass the features to the model.
output = model(features)

print(output)

tensor([[0.2792],
        [0.3092],
        [0.2924],
        [0.2878],
        [0.2826],
        [0.2812],
        [0.3064],
        [0.2945],
        [0.2884],
        [0.3056],
        [0.3052],
        [0.2791],
        [0.2797],
        [0.3003],
        [0.2956],
        [0.3036],
        [0.2987],
        [0.2965],
        [0.2922],
        [0.3058],
        [0.2949],
        [0.2824],
        [0.3097],
        [0.2842],
        [0.2843],
        [0.3000],
        [0.3012],
        [0.2955],
        [0.2936],
        [0.3083],
        [0.2816],
        [0.2787],
        [0.3077],
        [0.2754],
        [0.2772],
        [0.3132],
        [0.2917],
        [0.2970],
        [0.2792],
        [0.2871],
        [0.2837],
        [0.3079],
        [0.3009],
        [0.2856],
        [0.2959],
        [0.2974],
        [0.2981],
        [0.2801],
        [0.2971],
        [0.2829],
        [0.2921],
        [0.3054],
        [0.2969],
        [0.2936],
        [0.3066],
        [0

Finally, print the weights and biases of the middle layer of the network.


In [8]:
middel_layer: torch.nn.Linear = model.layers[0]

print(f"Weights: \n{middel_layer.weight}\n")
print(f"Bias: \n{middel_layer.bias}\n")

Weights: 
Parameter containing:
tensor([[-0.1612, -0.2794, -0.2504, -0.0655, -0.0396,  0.0536,  0.0538,  0.0168,
          0.0308],
        [-0.1718,  0.2937,  0.0543, -0.2672,  0.1476, -0.2866,  0.2967, -0.2505,
          0.0762],
        [ 0.0440, -0.2644,  0.1956,  0.2725,  0.2046,  0.2609,  0.2372,  0.0072,
          0.2277],
        [-0.1336,  0.2401,  0.0748, -0.1312, -0.1784, -0.2863, -0.0424,  0.3086,
         -0.2319],
        [ 0.2345, -0.0806, -0.3125, -0.1119,  0.1103,  0.0084, -0.0841,  0.2282,
          0.2974],
        [ 0.1433, -0.2609,  0.2830, -0.1433, -0.0071, -0.1993, -0.2669, -0.1360,
          0.2232],
        [-0.1766, -0.1993, -0.2856,  0.1435, -0.2625, -0.1050,  0.0118,  0.1706,
          0.1715],
        [-0.2380,  0.0285, -0.1728, -0.2613, -0.1109, -0.0566, -0.1146, -0.2859,
         -0.0775],
        [-0.2441, -0.1320,  0.1121,  0.0043,  0.0269,  0.0396, -0.1649,  0.0808,
         -0.1761]], requires_grad=True)

Bias: 
Parameter containing:
tensor([-0.0343, 